// Code generated by MockGen. DO NOT EDIT.
// Source: repository/user_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	models "github.com/wabtcdi/user_service/models"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *models.User, auth *models.UserAuthentication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user, auth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user, auth)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetUserAuthentication mocks base method.
func (m *MockUserRepository) GetUserAuthentication(ctx context.Context, userID uuid.UUID) (*models.UserAuthentication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAuthentication", ctx, userID)
	ret0, _ := ret[0].(*models.UserAuthentication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAuthentication indicates an expected call of GetUserAuthentication.
func (mr *MockUserRepositoryMockRecorder) GetUserAuthentication(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAuthentication", reflect.TypeOf((*MockUserRepository)(nil).GetUserAuthentication), ctx, userID)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, limit, offset int) ([]*models.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// MockAccessLevelRepository is a mock of AccessLevelRepository interface.
type MockAccessLevelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccessLevelRepositoryMockRecorder
}

// MockAccessLevelRepositoryMockRecorder is the mock recorder for MockAccessLevelRepository.
type MockAccessLevelRepositoryMockRecorder struct {
	mock *MockAccessLevelRepository
}

// NewMockAccessLevelRepository creates a new mock instance.
func NewMockAccessLevelRepository(ctrl *gomock.Controller) *MockAccessLevelRepository {
	mock := &MockAccessLevelRepository{ctrl: ctrl}
	mock.recorder = &MockAccessLevelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessLevelRepository) EXPECT() *MockAccessLevelRepositoryMockRecorder {
	return m.recorder
}

// AssignToUser mocks base method.
func (m *MockAccessLevelRepository) AssignToUser(ctx context.Context, userID uuid.UUID, accessLevelID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignToUser", ctx, userID, accessLevelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignToUser indicates an expected call of AssignToUser.
func (mr *MockAccessLevelRepositoryMockRecorder) AssignToUser(ctx, userID, accessLevelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignToUser", reflect.TypeOf((*MockAccessLevelRepository)(nil).AssignToUser), ctx, userID, accessLevelID)
}

// Create mocks base method.
func (m *MockAccessLevelRepository) Create(ctx context.Context, accessLevel *models.AccessLevel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, accessLevel)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccessLevelRepositoryMockRecorder) Create(ctx, accessLevel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccessLevelRepository)(nil).Create), ctx, accessLevel)
}

// GetByID mocks base method.
func (m *MockAccessLevelRepository) GetByID(ctx context.Context, id int) (*models.AccessLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.AccessLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccessLevelRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccessLevelRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockAccessLevelRepository) GetByName(ctx context.Context, name string) (*models.AccessLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*models.AccessLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockAccessLevelRepositoryMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockAccessLevelRepository)(nil).GetByName), ctx, name)
}

// GetUserAccessLevels mocks base method.
func (m *MockAccessLevelRepository) GetUserAccessLevels(ctx context.Context, userID uuid.UUID) ([]*models.AccessLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccessLevels", ctx, userID)
	ret0, _ := ret[0].([]*models.AccessLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccessLevels indicates an expected call of GetUserAccessLevels.
func (mr *MockAccessLevelRepositoryMockRecorder) GetUserAccessLevels(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccessLevels", reflect.TypeOf((*MockAccessLevelRepository)(nil).GetUserAccessLevels), ctx, userID)
}

// List mocks base method.
func (m *MockAccessLevelRepository) List(ctx context.Context) ([]*models.AccessLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*models.AccessLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccessLevelRepositoryMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccessLevelRepository)(nil).List), ctx)
}

// RemoveFromUser mocks base method.
func (m *MockAccessLevelRepository) RemoveFromUser(ctx context.Context, userID uuid.UUID, accessLevelID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromUser", ctx, userID, accessLevelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromUser indicates an expected call of RemoveFromUser.
func (mr *MockAccessLevelRepositoryMockRecorder) RemoveFromUser(ctx, userID, accessLevelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromUser", reflect.TypeOf((*MockAccessLevelRepository)(nil).RemoveFromUser), ctx, userID, accessLevelID)
}
