// Code generated by MockGen. DO NOT EDIT.
// Source: app.go

// Package cmd is a generated GoMock package.
package cmd

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServerStarter is a mock of ServerStarter interface.
type MockServerStarter struct {
	ctrl     *gomock.Controller
	recorder *MockServerStarterMockRecorder
}

// MockServerStarterMockRecorder is the mock recorder for MockServerStarter.
type MockServerStarterMockRecorder struct {
	mock *MockServerStarter
}

// NewMockServerStarter creates a new mock instance.
func NewMockServerStarter(ctrl *gomock.Controller) *MockServerStarter {
	mock := &MockServerStarter{ctrl: ctrl}
	mock.recorder = &MockServerStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerStarter) EXPECT() *MockServerStarterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockServerStarter) Start(addr string, handler http.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", addr, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerStarterMockRecorder) Start(addr, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServerStarter)(nil).Start), addr, handler)
}
